### ISSUE TITLE
Conflict OwinStartup

### ISSUE THREAD

**Issue by matteoventuri7** [uacaps/SignalRNotifications#1]
Hi,
from a fresh installation into clear MVC 5 project(from NuGet) i have this error:
The following errors occurred while attempting to load the app.
- The OwinStartup attribute discovered in assembly 'XXXXXX' referencing startup type 'XXXXX.Startup' conflicts with the attribute in assembly 'CAPS.Notifications.Web' referencing startup type 'CAPS.Notifications.Web.NotificationsConfig' because they have the same FriendlyName ''.

**Comment by matteoventuri7** [comment]
I try to execute "Update-Package Owin -reinstall" but problem persist.

**Comment by zaparker** [comment]
It looks like both your project and the CAPS.Notifications assembly have a OWINStartup attribute, and OWIN doesn't know which one to use since they are both un-named (and therefore have the same friendly name). Regarding multiple OWINStartup attributes, please see if the answer provided [here](http://stackoverflow.com/questions/19066781/is-it-not-possible-to-have-multiply-owinstartup-attributes) helps. I will try to add a new friendly name to my own startup class, but can't guarantee I'll be able to do it today.

**Comment by matteoventuri7** [comment]
no problem. thanks!!!
Il 18/mar/2015 17:48 "Zachary Parker" notifications@github.com ha scritto:

**Comment by zaparker** [comment]
The code has been updated, and the NuGet package has also been updated with the fix.

**Comment by matteoventuri7** [comment]
thank you so much
Il 18/mar/2015 21:13 "Zachary Parker" notifications@github.com ha scritto:

**Comment by zaparker** [comment]
Are you also using the Knockout component as well? I was thinking of adding
an Angular version so developers can choose based on which framework they
are using.

**Comment by matteoventuri7** [comment]
yes I'm using knockout component. In my opinion angular is the best choice.
Il 18/mar/2015 21:22 "Zachary Parker" notifications@github.com ha scritto:
